config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  resources :categories, only: [:show], path: 'kategorije'
  resources :questions, path: 'pitanja'
  resources :answers, path: 'odgovori' do
    member { post :vote }
  end

  root 'pages#home'
  get 'moja_pitanja' => 'pages#my_questions', as: 'my_questions'
  get 'moji_odgovori' => 'pages#my_answers', as: 'my_answers'
  get 'o_nama' => 'pages#about', as: 'about'
  get 'uslovi_koriscenja' => 'pages#agreements', as: 'agreements'

  resources :messages, only: [:new, :create], path: 'kontakt'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class='container'>
    <div class="row">
      <div class="col-xs-3 col-xs-offset-1 hidden-md hidden-lg">
        <div class="col-xs-12">
          <a href="https://www.facebook.com/pitamtecom">
            <i class="fa fa-facebook-square fa-2x"></i>
          </a>
        </div>
        <div class="col-xs-12">
          <a href="https://twitter.com/pitamtecom">
            <i class="fa fa-twitter-square fa-2x"></i>
          </a>
        </div>
      </div>
      <div class="col-xs-8 hidden-md hidden-lg agreement-links">
        <div class="col-xs-12">
          <%= link_to "Uslovi korišćenja", agreements_path %>
        </div>
        <div class="col-xs-12">
          <%= link_to "O nama", about_path %>
        </div>
        <div class="col-xs-12">
          <%= link_to "Kontakt", new_message_path %>
        </div>
      </div>
      <div class="col-md-12">
        <small>
          © 2015 PitamTe Team - All rights reserved 
        </small>
        <nav class="hidden-xs hidden-sm">
          <ul>
            <li><%= link_to "Uslovi korišćenja", agreements_path %></li>
            <li><%= link_to "O nama", about_path %></li>
            <li><%= link_to "Kontakt", new_message_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "PitamTe", root_path, id: "logo" %>
    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <nav>
      <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Početna", root_path %></li>
        <% if user_signed_in? %>
          <li class="hidden-xs hidden-sm">
            <div class="dropdown">
              <div id="dropdownUser" data-toggle="dropdown" aria-expanded="true">
                <%= current_user %>
                <span class="caret"></span>
              </div>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownUser">
                <li>
                  <span>
                    <i class='fa fa-question-circle'></i><%= link_to "Moja pitanja", my_questions_path %>
                  </span>
                </li>
                <li>
                  <span>
                    <i class='fa fa-exclamation-circle'></i><%= link_to "Moji odgovori", my_answers_path %>
                  </span>
                </li>
                <% if current_user.provider != "facebook" && current_user.provider != "twitter" %>
                  <li>
                    <span>
                      <i class='fa fa-user'></i><%= link_to "Detalji profila", edit_user_registration_path %>
                    </span>
                  </li>
                <% end %>
                <hr />
                <li>
                  <span>
                    <i class='fa fa-sign-out'></i><%= link_to "Odjavi se", destroy_user_session_path, :method => :delete %>
                  </span>
                </li>
              </ul>
            </div>
          </li>
          <li class="hidden-md hidden-lg">
            <%= link_to "Detalji profila", edit_user_registration_path %>
          </li>
          <li class="hidden-md hidden-lg">
            <%= link_to "Odjavi se", destroy_user_session_path, :method => :delete %>
          </li>
        <% else %>
          <li><%= link_to "Registruj se", new_user_registration_path %></li>
          <li><%= link_to "Prijavi se", new_user_session_path %></li>
        <% end %>
      </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
<head>
  <%= favicon_link_tag %>
  <%= metamagic site: "PitamTe", title: [:site, :title], separator: " — ", description: "Korisnici pitaju, korisnici odgovaraju." %>
  <meta property="og:type" content="question" />
  <meta property="og:image" content="http://i.imgur.com/sDEdPTs.png" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <div id="page-wrapper">
  	<%= render 'layouts/header' %>
    <div id='page-content'>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>